apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      name: spring-deployment
      labels:
        app: spring
    spec:
      containers:
      - name: spring
        image: rakhemanohar/spring:1.0
        ports:
        - containerPort: 8080

